GET http://localhost:3000/users

### 

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Junim",
  "email": "carlosssa@example.com"
}

###

GET http://localhost:3000/users/1

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "Carlos Silva"
}

###

DELETE http://localhost:3000/users/1